### ISSUE TITLE
IP

### ISSUE THREAD

**Issue by alekoren** [Driim/mikrotik_rkn#1]
Добрый день
прошу добавить в список rkn 
91.132.60.11/32
d.rutor.info

**Comment by Driim** [comment]
> 91.132.60

Здравствуйте! Я уже писал что список формируется автоматически на основе данных отсюда: https://github.com/zapret-info/z-i

Я не могу сюда ничего добавить. Точнее, если я добавлю, то данные просуществуют сутки, после обновления скриптом они исчезнут. Стоит писать сюда: https://github.com/zapret-info/z-i
