### ISSUE TITLE
Ошибки формирования subnets.rsc

### ISSUE THREAD

**Issue by Olegik-ah** [Driim/mikrotik_rkn#2]
Доброе время суток!
В последнее время наблюдаются баги с формированием subnets.rsc
1. файл subnets.rsc содержит только 1 строчку: /ip firewall address-list
2. файл subnets.rsc вообще пустой
Прошу подправить. Спасибо!

**Comment by Driim** [comment]
Поправлю!

**Comment by Driim** [comment]
Видимо при обновлении сервера что-то сломалось. Я в ручную закоммитил последние данные, найду время разберусь в чем там проблема.

**Comment by Driim** [comment]
Исправил ошибку, ежедневные обновления должны возобновиться.

**Comment by Olegik-ah** [comment]
Спасибо, все ок!
