### ISSUE TITLE
тянется не полный список. 

### ISSUE THREAD

**Issue by grinboy** [Driim/mikrotik_rkn#4]
при анализе файла которые нужно подгружать в микротик видно что не все адреса из реестра туда попадают т.е. по факту адрес в реестре есть (на блокировку) но в файле его нет.

37.1.216.89 вот этого адреса нет. При этом в полном дампе РКН он есть. Полный дамп я смотрел по ссылки   https://sourceforge.net/p/z-i/code-0/HEAD/tree/

**Comment by Driim** [comment]
Я думаю закрыли потому что поняли что список преобразовывается в подсети и потому конкретно этого IP-может не быть, но он будет в какой-то подсети.
