### ISSUE TITLE
No subnets.rsc updates

### ISSUE THREAD

**Issue by KuJIb6AH** [Driim/mikrotik_rkn#7]
Subnets.rsc is empty and hasn't been updated since 12 days :(
Been using your scripts for long time. Please fix

**Comment by Axxxolotl** [comment]
I implemented these scripts in my virtual machine, and now the actual list for installation in routeros can be downloaded here
https://www.mutabor.su/subnets.rsc
I will update and upload at least once an hour (if anyone needs it more often, let me know and I will correct the cron schedule).
But it will also depend on https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv. If this file stops updating, then my file will become useless.

**Comment by Driim** [comment]
https://sourceforge.net/p/z-i/code-0/HEAD/tree/dump.csv?format=raw becomes unavailable

**Comment by Driim** [comment]
switched to https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv
